name: Test batch_processing.sh

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - '*'

env:
  # Disable progress bars for less verbose output
  PIP_PROGRESS_BAR: "off"
  SCT_PROGRESS_BAR: "off"

jobs:
  batch_processing:
    name: Test batch_processing.sh
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]  # TODO: Change to [ ubuntu-18.04, macos-10.15 ]
                              # macOS currently fails due to https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3194
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout SCT
        uses: actions/checkout@v2

      - name: Platform
        run: |
          uname -a
          set

      - name: Install
        run: |
          pip3 install numpy

      - name: Test
        run: |
          ./rep2.py | tee rep2-test.txt

      - name: Validate new results
        run: |
          diff -u rep2-snapshot.txt rep2-test.txt
